version: "3.7"

services:

  nginx:
    image: "dainst/idai-portal-nginx:0.0.1"
    expose:
      - "80"
    networks:
      - "web"
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:test.idai.world,www.test.idai.world"
        - "traefik.port=80"
        
networks:
  web:
    external: true
