version: "3.7"

services:

  nginx:
    image: "dainst/idai-portal-nginx:0.0.1"
    volumes:
      - config:/app/config
    expose:
      - "80"
    networks:
      - "web"
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:idai.world,www.idai.world"
        - "traefik.port=80"

volumes:
  config:
    name: portal_config

networks:
  web:
    external: true
