version: "3.7"

services:

  nginx:
    image: "dainst/idai-portal-nginx:latest"
    expose:
      - "80"
    networks:
      - "web"
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:idai.world,www.idai.world"
        - "traefik.port=80"

networks:
  web:
    external: true
