name: ci

on:
  push:
    branches:
      - master
      - stable

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build Angular App
        run: export NODE_OPTIONS=--openssl-legacy-provider &&  yarn build

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref == 'refs/heads/stable' && 'stable' || 'latest' }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger image update via portainer
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ github.ref == 'refs/heads/stable' && secrets.WEBHOOK_URL_STABLE || secrets.WEBHOOK_URL_MASTER }}
          webhook_secret: 'no'
